//go:build linux

package main

import (
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/vishvananda/netlink"
	"github.com/vishvananda/netns"
	"golang.org/x/sys/unix"
)

// check12 — dual-stack (PRD v1.41). Unlike checks 1–11, which exercise the
// spike's own bpf/spike.c, this one loads the SHIPPING object
// (internal/datapath/bpf/kanea_bpfel.o) — the exact bytes kanead loads — and
// asks the questions v1.41 added to this spike's gate:
//
//	12a  the shipping object (4 progs, v6 maps incl. 20-byte keys) verifies
//	12b  disabled mode: config6 all-zero => ETH_P_IPV6 dropped, v4 undisturbed
//	12c  connect6 rewrites a native v6 VIP dial
//	12d  connect6 rewrites a v4-mapped dial (::ffff:a.b.c.d on AF_INET6)
//	12e  tc v6 policy: same-project passes, cross-project SYN drops,
//	     an allow edge opens it
//	12f  stats_svc folds both families into one frontend counter
//	12g  no autogenerated link-local (addr_gen_mode=1 + NODAD); external v6
//	     is ENETUNREACH immediately (cluster route, no default route)
//	12h  the egress guard drops the IMDS ULA fd00:ec2::254
//
// Everything here is torn down by the check itself; the ksp-/kspv- prefixes
// keep `-cleanup` effective after a crash.

const (
	shipObjDefault = "kanea_bpfel.o"

	gw6Str       = "fd10:244::1"
	clusterCIDR6 = "fd10:244::/56"
	svcCIDR6     = "fd10:245::/64"

	q1v4, q1v6 = "10.244.0.21", "fd10:244::21" // proj A, client
	q2v4, q2v6 = "10.244.0.22", "fd10:244::22" // proj A, server
	q3v4, q3v6 = "10.244.0.23", "fd10:244::23" // proj B, other

	twinVIP4 = "10.201.0.9"  // the v4 half of the twin frontend
	twinVIP6 = "fd10:245::9" // the v6 half
	twinSvc  = uint16(91)    // ONE frontend id for both families (§9.1)
	svcQ1    = uint32(111)   // shipping identity service ids
	svcQ2    = uint32(112)
	svcQ3    = uint32(121)
)

// shipEnv is the shipping object loaded beside the spike's own.
type shipEnv struct {
	coll   *ebpf.Collection
	link6  link.Link
	pinDir string
	pods   []string // pod ids created by this check, torn down in reverse
	e      *env
}

func check12(e *env) error {
	s := &shipEnv{e: e}
	defer s.teardown()

	shipObj := shipObjPath()
	if _, err := os.Stat(shipObj); err != nil {
		check("12a shipping object verifies at this kernel", false,
			fmt.Sprintf("%s not found — copy internal/datapath/bpf/kanea_bpfel.o beside the harness", shipObj))
		return nil
	}

	// 12a — the shipping object loads whole: all four programs (connect4,
	// connect6, both tc) and every map, including the 20-byte-key v6 ones.
	spec, err := ebpf.LoadCollectionSpec(shipObj)
	if err != nil {
		check("12a shipping object verifies at this kernel", false, err.Error())
		return nil
	}
	s.pinDir = pinRoot + "/ship"
	if err := os.MkdirAll(s.pinDir, 0o755); err != nil {
		return err
	}
	t0 := time.Now()
	coll, err := ebpf.NewCollectionWithOptions(spec, ebpf.CollectionOptions{
		Maps: ebpf.MapOptions{PinPath: s.pinDir},
	})
	if err != nil {
		check("12a shipping object verifies at this kernel", false, err.Error())
		return nil
	}
	s.coll = coll
	loadTime := time.Since(t0)
	names := []string{"kanea_connect4", "kanea_connect6", "kanea_to_container", "kanea_from_container"}
	missing := []string{}
	for _, n := range names {
		if coll.Programs[n] == nil {
			missing = append(missing, n)
		}
	}
	check("12a shipping object verifies at this kernel", len(missing) == 0,
		fmt.Sprintf("4 progs + %d maps in %v (missing: %v)", len(coll.Maps), loadTime.Round(time.Millisecond), missing))
	if len(missing) > 0 {
		return nil
	}

	// Attach the shipping connect6 at the root cgroup behind its own pinned
	// link, beside the spike's connect4 (different attach type, ALLOW_MULTI
	// posture identical to production).
	l6, err := link.AttachCgroup(link.CgroupOptions{
		Path:    cgroupRoot,
		Attach:  ebpf.AttachCGroupInet6Connect,
		Program: coll.Programs["kanea_connect6"],
	})
	if err != nil {
		check("12a connect6 attaches at the root cgroup", false, err.Error())
		return nil
	}
	s.link6 = l6
	pin := filepath.Join(s.pinDir, "link_connect6")
	_ = os.Remove(pin)
	if err := l6.Pin(pin); err != nil {
		check("12a connect6 link pins", false, err.Error())
		return nil
	}

	// Host state for the v6 half: forwarding on, the gw6 anchor on the dummy.
	if err := saveAndSetSysctl(e, "net/ipv6/conf/all/forwarding", "1"); err != nil {
		return err
	}
	dummy, err := netlink.LinkByName(dummyName)
	if err != nil {
		return err
	}
	gw6 := net.ParseIP(gw6Str)
	if err := netlink.AddrAdd(dummy, &netlink.Addr{
		IPNet: &net.IPNet{IP: gw6, Mask: net.CIDRMask(128, 128)},
		Flags: unix.IFA_F_NODAD,
	}); err != nil && !os.IsExist(err) {
		return fmt.Errorf("gw6 on dummy: %w", err)
	}

	// Host identities in the SHIPPING maps: gw4, uplink, gw6.
	for _, hostIP := range []net.IP{net.ParseIP(gwIPStr), e.uplinkIP, gw6} {
		if err := s.setIdentity(hostIP, 0, 0, flagHost); err != nil {
			return err
		}
	}
	// The v4 config (service-CIDR leak guard) for realism; config6 stays
	// ZERO for now — that is 12b's whole point.
	if err := s.setConfig4(svcCIDRStr); err != nil {
		return err
	}

	// Three dual-stack pods with the SHIPPING tc programs on their veths.
	for _, q := range []struct {
		id      string
		v4, v6  string
		project uint32
		service uint32
	}{
		{"q1", q1v4, q1v6, projA, svcQ1},
		{"q2", q2v4, q2v6, projA, svcQ2},
		{"q3", q3v4, q3v6, projB, svcQ3},
	} {
		if err := s.createDualPod(q.id, q.v4, q.v6, q.project, q.service); err != nil {
			return fmt.Errorf("create pod %s: %w", q.id, err)
		}
	}
	if err := startServer(e, "q2", backendPort); err != nil {
		return err
	}

	// 12b — DISABLED MODE FIRST: config6 is still all-zero (the map's birth
	// state), so ETH_P_IPV6 must drop at the tc hooks while v4 between the
	// same two pods is untouched. This is v1.41's one default-behavior change
	// on v4-only nodes.
	okV4, banner, _, errText, err := podConnect(e, "q1", fmt.Sprintf("%s:%d", q2v4, backendPort), 3*time.Second, false)
	if err != nil {
		return err
	}
	check("12b v4 between shipping-tc pods works with v6 disabled", okV4,
		pickDetail(okV4, "landed on "+bannerAddr(banner), errText))
	okV6, _, elapsed, errText, err := podConnect(e, "q1", fmt.Sprintf("[%s]:%d", q2v6, backendPort), 2*time.Second, false)
	if err != nil {
		return err
	}
	check("12b v6 dropped while config6 is zero (disabled mode)", !okV6,
		fmt.Sprintf("connect: %s after %v", errText, elapsed.Round(time.Millisecond)))

	// Enable v6: one write of config6, exactly what kanead's Init does.
	if err := s.setConfig6(svcCIDR6); err != nil {
		return err
	}

	// 12e(i) — same-project v6 now flows through the shipping policy.
	okV6, banner, _, errText, err = podConnect(e, "q1", fmt.Sprintf("[%s]:%d", q2v6, backendPort), 3*time.Second, false)
	if err != nil {
		return err
	}
	check("12e same-project v6 passes once config6 is written", okV6,
		pickDetail(okV6, "landed on "+bannerAddr(banner), errText))

	// The twin frontend: one svc_id, a v4 entry and a v6 entry, both -> q2.
	if err := s.setService4(twinVIP4, vipPort, twinSvc, 1, 1); err != nil {
		return err
	}
	if err := s.putBackend4(twinSvc, 0, 1, q2v4, backendPort); err != nil {
		return err
	}
	if err := s.setService6(twinVIP6, vipPort, twinSvc, 1, 1); err != nil {
		return err
	}
	if err := s.putBackend6(twinSvc, 0, 1, q2v6, backendPort); err != nil {
		return err
	}

	// 12c — a native v6 VIP dial from the host (the kanea-edge stand-in).
	banner, peer, _, err := hostDial(fmt.Sprintf("[%s]:%d", twinVIP6, vipPort), 3*time.Second)
	if err != nil {
		check("12c connect6 rewrites a native v6 VIP dial", false, err.Error())
	} else {
		check("12c connect6 rewrites a native v6 VIP dial",
			strings.Contains(bannerAddr(banner), q2v6),
			fmt.Sprintf("landed on %s (peer %s)", bannerAddr(banner), peer))
	}

	// 12d — a v4-mapped dial: an AF_INET6 socket connecting to
	// ::ffff:10.201.0.9 bypasses connect4 entirely; connect6's mapped branch
	// must rewrite word 3 against the v4 service table.
	banner, peer, err = v4MappedDial(twinVIP4, vipPort, 3*time.Second)
	if err != nil {
		check("12d connect6 rewrites a v4-mapped dial", false, err.Error())
	} else {
		check("12d connect6 rewrites a v4-mapped dial",
			strings.Contains(banner, q2v4),
			fmt.Sprintf("landed on %s (peer %s)", bannerAddr(banner), peer))
	}

	// 12e(ii) — cross-project v6 SYN drops; an allow edge opens it. Same
	// shape as check 5, against the shipping program and the v6 header path.
	dropsBefore := s.readDrops6(1 /* DROP_POLICY */)
	okX, _, elapsed, errText, err := podConnect(e, "q3", fmt.Sprintf("[%s]:%d", q2v6, backendPort), 2*time.Second, false)
	if err != nil {
		return err
	}
	dropsAfter := s.readDrops6(1)
	check("12e cross-project v6 SYN dropped", !okX && dropsAfter > dropsBefore,
		fmt.Sprintf("connect: %s after %v; policy drops6 %d -> %d",
			errText, elapsed.Round(time.Millisecond), dropsBefore, dropsAfter))

	if err := s.allowEdge(svcQ2, svcQ3); err != nil {
		return err
	}
	okX, banner, _, errText, err = podConnect(e, "q3", fmt.Sprintf("[%s]:%d", q2v6, backendPort), 3*time.Second, false)
	if err != nil {
		return err
	}
	check("12e an allow_v4 edge admits cross-project v6", okX,
		pickDetail(okX, "landed on "+bannerAddr(banner), errText))

	// 12f — one frontend counter for both families: the native v6 dial (12c)
	// and the v4-mapped dial (12d) both counted against twinSvc.
	connects := s.readSvcConnects(twinSvc)
	check("12f stats_svc folds both families into one frontend", connects >= 2,
		fmt.Sprintf("svc %d connects = %d (native v6 + v4-mapped)", twinSvc, connects))

	// 12g — the kernel-behavior half of the NODAD design: eth0 carries
	// exactly the static /128 (no autogenerated link-local), and external v6
	// is ENETUNREACH immediately because the only v6 route is the cluster
	// CIDR — deliberately not a default route.
	extra, err := s.nonStaticV6Addrs("q1")
	if err != nil {
		return err
	}
	check("12g no autogenerated link-local (addr_gen_mode=1, NODAD)", len(extra) == 0,
		fmt.Sprintf("non-static v6 addrs on eth0: %v", extra))

	t1 := time.Now()
	okExt, _, _, errText, err := podConnect(e, "q1", "[2001:db8::1]:80", 3*time.Second, false)
	if err != nil {
		return err
	}
	fast := time.Since(t1) < 1500*time.Millisecond
	check("12g external v6 fails fast (no default route, no NAT66)",
		!okExt && strings.Contains(errText, "unreachable") && fast,
		fmt.Sprintf("connect: %s", errText))

	// 12h — the IMDS ULA is dropped in the kernel even when a route would
	// carry it: give q3 a v6 default route, then dial fd00:ec2::254.
	if err := s.addDefaultRoute6("q3"); err != nil {
		return err
	}
	metaBefore := s.readDrops6(2 /* DROP_METADATA */)
	okMeta, _, _, errText, err := podConnect(e, "q3", "[fd00:ec2::254]:80", 2*time.Second, false)
	if err != nil {
		return err
	}
	metaAfter := s.readDrops6(2)
	check("12h egress guard drops the IMDS ULA fd00:ec2::254", !okMeta && metaAfter > metaBefore,
		fmt.Sprintf("connect: %s; metadata drops6 %d -> %d", errText, metaBefore, metaAfter))

	// Passive observation: the kernel's own MLD chatter (ff02::16 joins for
	// the solicited-node groups) lands in DROP_LINK_LOCAL — visible, never
	// silent, and nothing legitimate needs it with static neighbors.
	info("12i link-local/multicast drops6 (MLD etc.)",
		fmt.Sprintf("%d packets", s.readDrops6(5 /* DROP_LINK_LOCAL */)))
	return nil
}

func shipObjPath() string {
	if p := os.Getenv("KANEA_SHIP_OBJ"); p != "" {
		return p
	}
	if _, err := os.Stat(shipObjDefault); err == nil {
		return shipObjDefault
	}
	return "../../internal/datapath/bpf/kanea_bpfel.o"
}

func pickDetail(ok bool, okDetail, errText string) string {
	if ok {
		return okDetail
	}
	return "connect failed: " + errText
}

// ---- shipping-map layouts (mirror internal/datapath/dpmap byte-for-byte) ----

type svcKey6 struct {
	IP    [16]byte
	Port  [2]byte
	Proto uint8
	Pad   uint8
}

type backendVal6 struct {
	IP   [16]byte
	Port [2]byte
	Pad  uint16
}

type shipConfig4 struct {
	Net  [4]byte
	Mask [4]byte
}

type shipConfig6 struct {
	Net  [16]byte
	Mask [16]byte
}

type shipDropKey6 struct {
	DstIP  [16]byte
	Reason uint8
	Pad    [3]byte
}

func be16(ip net.IP) [16]byte {
	var b [16]byte
	copy(b[:], ip.To16())
	return b
}

func maskBytes(n *net.IPNet, width int) []byte {
	m := make([]byte, width)
	copy(m, n.Mask)
	return m
}

func (s *shipEnv) mp(name string) *ebpf.Map { return s.coll.Maps[name] }

func (s *shipEnv) setIdentity(ip net.IP, project, service, flags uint32) error {
	v := identityVal{ProjectID: project, ServiceID: service, Flags: flags}
	if ip4 := ip.To4(); ip4 != nil {
		return s.mp("identity_v4").Put(be4(ip4), v)
	}
	return s.mp("identity_v6").Put(be16(ip), v)
}

func (s *shipEnv) allowEdge(dst, src uint32) error {
	return s.mp("allow_v4").Put(allowKey{DstServiceID: dst, SrcServiceID: src}, uint8(1))
}

func (s *shipEnv) setService4(vip string, port uint16, svcID, count uint16, gen uint32) error {
	return s.mp("svc_v4").Put(newSvcKey(vip, port), svcVal{SvcID: svcID, Count: count, Gen: gen})
}

func (s *shipEnv) putBackend4(svcID, index uint16, gen uint32, ip string, port uint16) error {
	return s.mp("svc_backends").Put(
		backendKey{SvcID: svcID, Index: index, Gen: gen},
		backendVal{IP: be4(net.ParseIP(ip)), Port: be2(port)})
}

func (s *shipEnv) setService6(vip string, port uint16, svcID, count uint16, gen uint32) error {
	k := svcKey6{IP: be16(net.ParseIP(vip)), Port: be2(port), Proto: protoTCP}
	return s.mp("svc_v6").Put(k, svcVal{SvcID: svcID, Count: count, Gen: gen})
}

func (s *shipEnv) putBackend6(svcID, index uint16, gen uint32, ip string, port uint16) error {
	return s.mp("svc_backends6").Put(
		backendKey{SvcID: svcID, Index: index, Gen: gen},
		backendVal6{IP: be16(net.ParseIP(ip)), Port: be2(port)})
}

func (s *shipEnv) setConfig4(cidr string) error {
	n := mustCIDR(cidr)
	var v shipConfig4
	copy(v.Net[:], n.IP.To4())
	copy(v.Mask[:], maskBytes(n, 4))
	return s.mp("config").Put(uint32(0), v)
}

func (s *shipEnv) setConfig6(cidr string) error {
	n := mustCIDR(cidr)
	var v shipConfig6
	copy(v.Net[:], n.IP.To16())
	copy(v.Mask[:], maskBytes(n, 16))
	return s.mp("config6").Put(uint32(0), v)
}

// readSvcConnects sums the per-cpu connect counter for one frontend id in
// the SHIPPING stats_svc (a bare __u16 key, unlike the spike's own).
func (s *shipEnv) readSvcConnects(svcID uint16) uint64 {
	var per []uint64
	if err := s.mp("stats_svc").Lookup(svcID, &per); err != nil {
		return 0
	}
	var sum uint64
	for _, v := range per {
		sum += v
	}
	return sum
}

// readDrops6 sums stats_drops6 across destinations for one reason.
func (s *shipEnv) readDrops6(reason uint8) uint64 {
	m := s.mp("stats_drops6")
	var (
		key shipDropKey6
		per []uint64
		sum uint64
	)
	it := m.Iterate()
	for it.Next(&key, &per) {
		if key.Reason != reason {
			continue
		}
		for _, v := range per {
			sum += v
		}
	}
	return sum
}

// ---- dual-stack plumbing (the createPod of plumb.go, both families,
// shipping tc programs, and the v1.41 sysctl posture) ----

func (s *shipEnv) createDualPod(id, ip4Str, ip6Str string, project, service uint32) error {
	e := s.e
	p := &pod{
		id:      id,
		ns:      nsPrefix + id,
		ip:      net.ParseIP(ip4Str).To4(),
		veth:    vePrefix + id,
		project: project,
		service: service,
	}
	ip6 := net.ParseIP(ip6Str)
	gw6 := net.ParseIP(gw6Str)

	if out, err := exec.Command("ip", "netns", "add", p.ns).CombinedOutput(); err != nil {
		return fmt.Errorf("ip netns add: %v: %s", err, out)
	}
	nsh, err := netns.GetFromName(p.ns)
	if err != nil {
		return err
	}
	defer nsh.Close()
	nl, err := netlink.NewHandleAt(nsh)
	if err != nil {
		return err
	}
	defer nl.Close()

	peerName := pePrefix + id
	if err := netlink.LinkAdd(&netlink.Veth{
		LinkAttrs: netlink.LinkAttrs{Name: p.veth}, PeerName: peerName,
	}); err != nil {
		return err
	}
	// Deterministic MACs, race-free against udev's MACAddressPolicy — the same
	// discipline plumb.go's createPod documents (settle after add, set the
	// chosen address at the last moment, program neighbors from it).
	settleUdev()
	hostMAC := deterministicMAC(0x02, p.ip)
	peerMAC := deterministicMAC(0x06, p.ip)
	host, err := netlink.LinkByName(p.veth)
	if err != nil {
		return err
	}
	if err := netlink.LinkSetAlias(host, fmt.Sprintf("kanea/%s/%s,%s", id, p.ip, ip6)); err != nil {
		return err
	}

	// SHIPPING tc programs, before the interface ever carries a packet.
	if err := attachTC(host.Attrs().Index,
		s.coll.Programs["kanea_to_container"], s.coll.Programs["kanea_from_container"]); err != nil {
		return err
	}

	peer, err := netlink.LinkByName(peerName)
	if err != nil {
		return err
	}
	if err := netlink.LinkSetNsFd(peer, int(nsh)); err != nil {
		return err
	}
	inner, err := nl.LinkByName(peerName)
	if err != nil {
		return err
	}
	if err := nl.LinkSetName(inner, "eth0"); err != nil {
		return err
	}

	// The v1.41 sysctl posture, before the link comes up: addressing is
	// kanead's, so no RA, no autoconf, and no autogenerated link-local.
	for _, kv := range [][2]string{
		{"net/ipv6/conf/eth0/accept_ra", "0"},
		{"net/ipv6/conf/eth0/autoconf", "0"},
		{"net/ipv6/conf/eth0/addr_gen_mode", "1"},
	} {
		if out, err := exec.Command("ip", "netns", "exec", p.ns, "sh", "-c",
			fmt.Sprintf("echo %s > /proc/sys/%s", kv[1], kv[0])).CombinedOutput(); err != nil {
			return fmt.Errorf("sysctl %s in %s: %v: %s", kv[0], p.ns, err, out)
		}
	}

	eth0, err := nl.LinkByName("eth0")
	if err != nil {
		return err
	}
	// The peer's MAC is set inside the fresh netns, where no policy runs.
	if err := nl.LinkSetHardwareAddr(eth0, peerMAC); err != nil {
		return err
	}
	if lo, err := nl.LinkByName("lo"); err == nil {
		_ = nl.LinkSetUp(lo)
	}
	if err := nl.AddrAdd(eth0, &netlink.Addr{IPNet: ipnet32(p.ip)}); err != nil {
		return err
	}
	if err := nl.AddrAdd(eth0, &netlink.Addr{
		IPNet: &net.IPNet{IP: ip6, Mask: net.CIDRMask(128, 128)},
		Flags: unix.IFA_F_NODAD,
	}); err != nil {
		return err
	}
	if err := nl.LinkSetUp(eth0); err != nil {
		return err
	}

	gw := net.ParseIP(gwIPStr).To4()
	if err := nl.RouteAdd(&netlink.Route{
		LinkIndex: eth0.Attrs().Index, Dst: ipnet32(gw), Scope: netlink.SCOPE_LINK,
	}); err != nil {
		return err
	}
	if err := nl.RouteAdd(&netlink.Route{LinkIndex: eth0.Attrs().Index, Gw: gw}); err != nil {
		return err
	}
	// The v6 trio: gw /128 scope-link, then the CLUSTER route — deliberately
	// not a default route (external v6 must be ENETUNREACH, 12g).
	if err := nl.RouteAdd(&netlink.Route{
		LinkIndex: eth0.Attrs().Index,
		Dst:       &net.IPNet{IP: gw6, Mask: net.CIDRMask(128, 128)},
		Scope:     netlink.SCOPE_LINK,
	}); err != nil {
		return err
	}
	if err := nl.RouteAdd(&netlink.Route{
		LinkIndex: eth0.Attrs().Index, Dst: mustCIDR(clusterCIDR6), Gw: gw6,
	}); err != nil {
		return err
	}

	// In-ns gateway neighbors, both families, from the host MAC we chose.
	for _, n := range []*netlink.Neigh{
		{LinkIndex: eth0.Attrs().Index, IP: gw, HardwareAddr: hostMAC, State: netlink.NUD_PERMANENT},
		{LinkIndex: eth0.Attrs().Index, IP: gw6, HardwareAddr: hostMAC, State: netlink.NUD_PERMANENT, Family: unix.AF_INET6},
	} {
		if err := nl.NeighAdd(n); err != nil {
			return fmt.Errorf("in-ns neigh %s: %w", n.IP, err)
		}
	}

	// Identities for BOTH families in the shipping maps, before the routes
	// exist (the deny-closed order).
	if err := s.setIdentity(p.ip, project, service, 0); err != nil {
		return err
	}
	if err := s.setIdentity(ip6, project, service, 0); err != nil {
		return err
	}

	// Host MAC set and link up in immediate succession; the host->pod
	// neighbors go in AFTER up so they stay NUD_PERMANENT (plumb.go's 7c fix).
	if err := netlink.LinkSetHardwareAddr(host, hostMAC); err != nil {
		return err
	}
	if err := netlink.LinkSetUp(host); err != nil {
		return err
	}
	for _, n := range []*netlink.Neigh{
		{LinkIndex: host.Attrs().Index, IP: p.ip, HardwareAddr: peerMAC, State: netlink.NUD_PERMANENT},
		{LinkIndex: host.Attrs().Index, IP: ip6, HardwareAddr: peerMAC, State: netlink.NUD_PERMANENT, Family: unix.AF_INET6},
	} {
		if err := netlink.NeighAdd(n); err != nil {
			return fmt.Errorf("host neigh %s: %w", n.IP, err)
		}
	}
	if err := netlink.RouteAdd(&netlink.Route{
		LinkIndex: host.Attrs().Index, Dst: ipnet32(p.ip),
		Scope: netlink.SCOPE_LINK, Src: net.ParseIP(gwIPStr).To4(),
	}); err != nil {
		return err
	}
	if err := netlink.RouteAdd(&netlink.Route{
		LinkIndex: host.Attrs().Index,
		Dst:       &net.IPNet{IP: ip6, Mask: net.CIDRMask(128, 128)},
		Src:       gw6,
	}); err != nil {
		return fmt.Errorf("host /128 route: %w", err)
	}

	e.pods[id] = p
	s.pods = append(s.pods, id)
	return nil
}

// nonStaticV6Addrs lists eth0's v6 addresses other than the one static /128.
func (s *shipEnv) nonStaticV6Addrs(id string) ([]string, error) {
	p := s.e.pods[id]
	nsh, err := netns.GetFromName(p.ns)
	if err != nil {
		return nil, err
	}
	defer nsh.Close()
	nl, err := netlink.NewHandleAt(nsh)
	if err != nil {
		return nil, err
	}
	defer nl.Close()
	eth0, err := nl.LinkByName("eth0")
	if err != nil {
		return nil, err
	}
	addrs, err := nl.AddrList(eth0, netlink.FAMILY_V6)
	if err != nil {
		return nil, err
	}
	extra := []string{}
	for _, a := range addrs {
		if a.IP.To4() == nil && a.IP.IsGlobalUnicast() {
			continue // the static address
		}
		extra = append(extra, a.IP.String())
	}
	return extra, nil
}

func (s *shipEnv) addDefaultRoute6(id string) error {
	p := s.e.pods[id]
	nsh, err := netns.GetFromName(p.ns)
	if err != nil {
		return err
	}
	defer nsh.Close()
	nl, err := netlink.NewHandleAt(nsh)
	if err != nil {
		return err
	}
	defer nl.Close()
	eth0, err := nl.LinkByName("eth0")
	if err != nil {
		return err
	}
	return nl.RouteAdd(&netlink.Route{
		LinkIndex: eth0.Attrs().Index, Gw: net.ParseIP(gw6Str),
	})
}

// v4MappedDial opens an AF_INET6 socket and connects to ::ffff:<vip>:<port> —
// the path that bypasses the connect4 hook entirely. Returns the banner and
// the kernel's getpeername (the rewritten, still v4-mapped destination).
func v4MappedDial(vip string, port int, timeout time.Duration) (banner, peer string, err error) {
	fd, err := unix.Socket(unix.AF_INET6, unix.SOCK_STREAM|unix.SOCK_CLOEXEC, 0)
	if err != nil {
		return "", "", err
	}
	tv := unix.NsecToTimeval(timeout.Nanoseconds())
	_ = unix.SetsockoptTimeval(fd, unix.SOL_SOCKET, unix.SO_SNDTIMEO, &tv)
	_ = unix.SetsockoptTimeval(fd, unix.SOL_SOCKET, unix.SO_RCVTIMEO, &tv)

	sa := &unix.SockaddrInet6{Port: port}
	copy(sa.Addr[:], net.ParseIP(vip).To16()) // To16 of a v4 IP IS the mapped form
	if err := unix.Connect(fd, sa); err != nil {
		_ = unix.Close(fd)
		return "", "", fmt.Errorf("connect ::ffff:%s: %w", vip, err)
	}
	if got, err := unix.Getpeername(fd); err == nil {
		if sa6, ok := got.(*unix.SockaddrInet6); ok {
			peer = fmt.Sprintf("[%s]:%d", net.IP(sa6.Addr[:]), sa6.Port)
		}
	}
	f := os.NewFile(uintptr(fd), "v4mapped")
	defer f.Close()
	conn, err := net.FileConn(f)
	if err != nil {
		return "", peer, err
	}
	defer conn.Close()
	_ = conn.SetReadDeadline(time.Now().Add(timeout))
	buf := make([]byte, 128)
	n, err := conn.Read(buf)
	if err != nil {
		return "", peer, fmt.Errorf("read banner: %w", err)
	}
	return strings.TrimSpace(string(buf[:n])), peer, nil
}

func (s *shipEnv) teardown() {
	e := s.e
	// Kill only the servers started for q-pods; harness teardown handles the
	// rest. Pods first (their veths carry the shipping tc programs).
	for i := len(s.pods) - 1; i >= 0; i-- {
		deletePod(e, s.pods[i])
	}
	if dummy, err := netlink.LinkByName(dummyName); err == nil {
		gw6 := net.ParseIP(gw6Str)
		_ = netlink.AddrDel(dummy, &netlink.Addr{
			IPNet: &net.IPNet{IP: gw6, Mask: net.CIDRMask(128, 128)},
		})
	}
	if s.link6 != nil {
		_ = s.link6.Unpin()
		_ = s.link6.Close()
	}
	if s.coll != nil {
		s.coll.Close()
	}
	if s.pinDir != "" {
		_ = os.RemoveAll(s.pinDir)
	}
}
