//go:build linux

//go:generate sh -c "echo 'the BPF artifacts are regenerated by <make bpf> (digest-pinned toolchain container), not by go generate: see the repository Makefile' >&2; exit 1"

// The package documentation lives in export.go, which builds on every
// platform; this file only carries the go:generate guard above.

package bpf
