// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type kaneaAllowKey struct {
	_            structs.HostLayout
	DstServiceId uint32
	SrcServiceId uint32
}

type kaneaBackendKey struct {
	_     structs.HostLayout
	SvcId uint16
	Index uint16
	Gen   uint32
}

type kaneaBackendVal struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	Pad  uint16
}

type kaneaBackendVal6 struct {
	_    structs.HostLayout
	Ip   [4]uint32
	Port uint16
	Pad  uint16
}

type kaneaDpCidr struct {
	_    structs.HostLayout
	Net  uint32
	Mask uint32
}

type kaneaDpCidr6 struct {
	_    structs.HostLayout
	Net  [4]uint32
	Mask [4]uint32
}

type kaneaDpConfig struct {
	_               structs.HostLayout
	ServiceCidrNet  uint32
	ServiceCidrMask uint32
}

type kaneaDpConfig6 struct {
	_    structs.HostLayout
	Net  [4]uint32
	Mask [4]uint32
}

type kaneaDropKey struct {
	_      structs.HostLayout
	DstIp  uint32
	Reason uint8
	Pad    [3]uint8
}

type kaneaDropKey6 struct {
	_      structs.HostLayout
	DstIp  [4]uint32
	Reason uint8
	Pad    [3]uint8
}

type kaneaEpStats struct {
	_       structs.HostLayout
	RxBytes uint64
	RxPkts  uint64
	TxBytes uint64
	TxPkts  uint64
}

type kaneaIdentity struct {
	_         structs.HostLayout
	ProjectId uint32
	ServiceId uint32
	Flags     uint32
}

type kaneaIn6Addr struct {
	_        structs.HostLayout
	S6Addr32 [4]uint32
}

type kaneaSvcKey struct {
	_     structs.HostLayout
	Vip   uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

type kaneaSvcKey6 struct {
	_     structs.HostLayout
	Vip   [4]uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

type kaneaSvcVal struct {
	_     structs.HostLayout
	SvcId uint16
	Count uint16
	Gen   uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	kaneaMapAllowV4             = "allow_v4"
	kaneaMapClusterV4           = "cluster_v4"
	kaneaMapClusterV6           = "cluster_v6"
	kaneaMapConfig              = "config"
	kaneaMapConfig6             = "config6"
	kaneaMapIdentityV4          = "identity_v4"
	kaneaMapIdentityV6          = "identity_v6"
	kaneaMapStatsDrops          = "stats_drops"
	kaneaMapStatsDrops6         = "stats_drops6"
	kaneaMapStatsEp             = "stats_ep"
	kaneaMapStatsEp6            = "stats_ep6"
	kaneaMapStatsSvc            = "stats_svc"
	kaneaMapSvcBackends         = "svc_backends"
	kaneaMapSvcBackends6        = "svc_backends6"
	kaneaMapSvcV4               = "svc_v4"
	kaneaMapSvcV6               = "svc_v6"
	kaneaProgKaneaConnect4      = "kanea_connect4"
	kaneaProgKaneaConnect6      = "kanea_connect6"
	kaneaProgKaneaFromContainer = "kanea_from_container"
	kaneaProgKaneaToContainer   = "kanea_to_container"
)

// loadKanea returns the embedded CollectionSpec for kanea.
func loadKanea() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KaneaBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kanea: %w", err)
	}

	return spec, err
}

// loadKaneaObjects loads kanea and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kaneaObjects
//	*kaneaPrograms
//	*kaneaMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKaneaObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadKanea()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kaneaSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kaneaSpecs struct {
	kaneaProgramSpecs
	kaneaMapSpecs
	kaneaVariableSpecs
}

// kaneaProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kaneaProgramSpecs struct {
	KaneaConnect4      *ebpf.ProgramSpec `ebpf:"kanea_connect4"`
	KaneaConnect6      *ebpf.ProgramSpec `ebpf:"kanea_connect6"`
	KaneaFromContainer *ebpf.ProgramSpec `ebpf:"kanea_from_container"`
	KaneaToContainer   *ebpf.ProgramSpec `ebpf:"kanea_to_container"`
}

// kaneaMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kaneaMapSpecs struct {
	AllowV4      *ebpf.MapSpec `ebpf:"allow_v4"`
	ClusterV4    *ebpf.MapSpec `ebpf:"cluster_v4"`
	ClusterV6    *ebpf.MapSpec `ebpf:"cluster_v6"`
	Config       *ebpf.MapSpec `ebpf:"config"`
	Config6      *ebpf.MapSpec `ebpf:"config6"`
	IdentityV4   *ebpf.MapSpec `ebpf:"identity_v4"`
	IdentityV6   *ebpf.MapSpec `ebpf:"identity_v6"`
	StatsDrops   *ebpf.MapSpec `ebpf:"stats_drops"`
	StatsDrops6  *ebpf.MapSpec `ebpf:"stats_drops6"`
	StatsEp      *ebpf.MapSpec `ebpf:"stats_ep"`
	StatsEp6     *ebpf.MapSpec `ebpf:"stats_ep6"`
	StatsSvc     *ebpf.MapSpec `ebpf:"stats_svc"`
	SvcBackends  *ebpf.MapSpec `ebpf:"svc_backends"`
	SvcBackends6 *ebpf.MapSpec `ebpf:"svc_backends6"`
	SvcV4        *ebpf.MapSpec `ebpf:"svc_v4"`
	SvcV6        *ebpf.MapSpec `ebpf:"svc_v6"`
}

// kaneaVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kaneaVariableSpecs struct {
}

// kaneaObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKaneaObjects or ebpf.CollectionSpec.LoadAndAssign.
type kaneaObjects struct {
	kaneaPrograms
	kaneaMaps
	kaneaVariables
}

func (o *kaneaObjects) Close() error {
	return _KaneaClose(
		&o.kaneaPrograms,
		&o.kaneaMaps,
	)
}

// kaneaMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKaneaObjects or ebpf.CollectionSpec.LoadAndAssign.
type kaneaMaps struct {
	AllowV4      *ebpf.Map `ebpf:"allow_v4"`
	ClusterV4    *ebpf.Map `ebpf:"cluster_v4"`
	ClusterV6    *ebpf.Map `ebpf:"cluster_v6"`
	Config       *ebpf.Map `ebpf:"config"`
	Config6      *ebpf.Map `ebpf:"config6"`
	IdentityV4   *ebpf.Map `ebpf:"identity_v4"`
	IdentityV6   *ebpf.Map `ebpf:"identity_v6"`
	StatsDrops   *ebpf.Map `ebpf:"stats_drops"`
	StatsDrops6  *ebpf.Map `ebpf:"stats_drops6"`
	StatsEp      *ebpf.Map `ebpf:"stats_ep"`
	StatsEp6     *ebpf.Map `ebpf:"stats_ep6"`
	StatsSvc     *ebpf.Map `ebpf:"stats_svc"`
	SvcBackends  *ebpf.Map `ebpf:"svc_backends"`
	SvcBackends6 *ebpf.Map `ebpf:"svc_backends6"`
	SvcV4        *ebpf.Map `ebpf:"svc_v4"`
	SvcV6        *ebpf.Map `ebpf:"svc_v6"`
}

func (m *kaneaMaps) Close() error {
	return _KaneaClose(
		m.AllowV4,
		m.ClusterV4,
		m.ClusterV6,
		m.Config,
		m.Config6,
		m.IdentityV4,
		m.IdentityV6,
		m.StatsDrops,
		m.StatsDrops6,
		m.StatsEp,
		m.StatsEp6,
		m.StatsSvc,
		m.SvcBackends,
		m.SvcBackends6,
		m.SvcV4,
		m.SvcV6,
	)
}

// kaneaVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKaneaObjects or ebpf.CollectionSpec.LoadAndAssign.
type kaneaVariables struct {
}

// kaneaPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKaneaObjects or ebpf.CollectionSpec.LoadAndAssign.
type kaneaPrograms struct {
	KaneaConnect4      *ebpf.Program `ebpf:"kanea_connect4"`
	KaneaConnect6      *ebpf.Program `ebpf:"kanea_connect6"`
	KaneaFromContainer *ebpf.Program `ebpf:"kanea_from_container"`
	KaneaToContainer   *ebpf.Program `ebpf:"kanea_to_container"`
}

func (p *kaneaPrograms) Close() error {
	return _KaneaClose(
		p.KaneaConnect4,
		p.KaneaConnect6,
		p.KaneaFromContainer,
		p.KaneaToContainer,
	)
}

func _KaneaClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kanea_bpfeb.o
var _KaneaBytes []byte
