// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type kaneaAllowKey struct {
	_            structs.HostLayout
	DstServiceId uint32
	SrcServiceId uint32
}

type kaneaBackendKey struct {
	_     structs.HostLayout
	SvcId uint16
	Index uint16
	Gen   uint32
}

type kaneaBackendVal struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	Pad  uint16
}

type kaneaDpConfig struct {
	_               structs.HostLayout
	ServiceCidrNet  uint32
	ServiceCidrMask uint32
}

type kaneaDropKey struct {
	_      structs.HostLayout
	DstIp  uint32
	Reason uint8
	Pad    [3]uint8
}

type kaneaEpStats struct {
	_       structs.HostLayout
	RxBytes uint64
	RxPkts  uint64
	TxBytes uint64
	TxPkts  uint64
}

type kaneaIdentity struct {
	_         structs.HostLayout
	ProjectId uint32
	ServiceId uint32
	Flags     uint32
}

type kaneaSvcKey struct {
	_     structs.HostLayout
	Vip   uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

type kaneaSvcVal struct {
	_     structs.HostLayout
	SvcId uint16
	Count uint16
	Gen   uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	kaneaMapAllowV4             = "allow_v4"
	kaneaMapConfig              = "config"
	kaneaMapIdentityV4          = "identity_v4"
	kaneaMapStatsDrops          = "stats_drops"
	kaneaMapStatsEp             = "stats_ep"
	kaneaMapStatsSvc            = "stats_svc"
	kaneaMapSvcBackends         = "svc_backends"
	kaneaMapSvcV4               = "svc_v4"
	kaneaProgKaneaConnect4      = "kanea_connect4"
	kaneaProgKaneaFromContainer = "kanea_from_container"
	kaneaProgKaneaToContainer   = "kanea_to_container"
)

// loadKanea returns the embedded CollectionSpec for kanea.
func loadKanea() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KaneaBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kanea: %w", err)
	}

	return spec, err
}

// loadKaneaObjects loads kanea and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kaneaObjects
//	*kaneaPrograms
//	*kaneaMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKaneaObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadKanea()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kaneaSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kaneaSpecs struct {
	kaneaProgramSpecs
	kaneaMapSpecs
	kaneaVariableSpecs
}

// kaneaProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kaneaProgramSpecs struct {
	KaneaConnect4      *ebpf.ProgramSpec `ebpf:"kanea_connect4"`
	KaneaFromContainer *ebpf.ProgramSpec `ebpf:"kanea_from_container"`
	KaneaToContainer   *ebpf.ProgramSpec `ebpf:"kanea_to_container"`
}

// kaneaMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kaneaMapSpecs struct {
	AllowV4     *ebpf.MapSpec `ebpf:"allow_v4"`
	Config      *ebpf.MapSpec `ebpf:"config"`
	IdentityV4  *ebpf.MapSpec `ebpf:"identity_v4"`
	StatsDrops  *ebpf.MapSpec `ebpf:"stats_drops"`
	StatsEp     *ebpf.MapSpec `ebpf:"stats_ep"`
	StatsSvc    *ebpf.MapSpec `ebpf:"stats_svc"`
	SvcBackends *ebpf.MapSpec `ebpf:"svc_backends"`
	SvcV4       *ebpf.MapSpec `ebpf:"svc_v4"`
}

// kaneaVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kaneaVariableSpecs struct {
}

// kaneaObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKaneaObjects or ebpf.CollectionSpec.LoadAndAssign.
type kaneaObjects struct {
	kaneaPrograms
	kaneaMaps
	kaneaVariables
}

func (o *kaneaObjects) Close() error {
	return _KaneaClose(
		&o.kaneaPrograms,
		&o.kaneaMaps,
	)
}

// kaneaMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKaneaObjects or ebpf.CollectionSpec.LoadAndAssign.
type kaneaMaps struct {
	AllowV4     *ebpf.Map `ebpf:"allow_v4"`
	Config      *ebpf.Map `ebpf:"config"`
	IdentityV4  *ebpf.Map `ebpf:"identity_v4"`
	StatsDrops  *ebpf.Map `ebpf:"stats_drops"`
	StatsEp     *ebpf.Map `ebpf:"stats_ep"`
	StatsSvc    *ebpf.Map `ebpf:"stats_svc"`
	SvcBackends *ebpf.Map `ebpf:"svc_backends"`
	SvcV4       *ebpf.Map `ebpf:"svc_v4"`
}

func (m *kaneaMaps) Close() error {
	return _KaneaClose(
		m.AllowV4,
		m.Config,
		m.IdentityV4,
		m.StatsDrops,
		m.StatsEp,
		m.StatsSvc,
		m.SvcBackends,
		m.SvcV4,
	)
}

// kaneaVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKaneaObjects or ebpf.CollectionSpec.LoadAndAssign.
type kaneaVariables struct {
}

// kaneaPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKaneaObjects or ebpf.CollectionSpec.LoadAndAssign.
type kaneaPrograms struct {
	KaneaConnect4      *ebpf.Program `ebpf:"kanea_connect4"`
	KaneaFromContainer *ebpf.Program `ebpf:"kanea_from_container"`
	KaneaToContainer   *ebpf.Program `ebpf:"kanea_to_container"`
}

func (p *kaneaPrograms) Close() error {
	return _KaneaClose(
		p.KaneaConnect4,
		p.KaneaFromContainer,
		p.KaneaToContainer,
	)
}

func _KaneaClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kanea_bpfeb.o
var _KaneaBytes []byte
