package network

import (
	"bytes"
	"fmt"
	"net"
	"net/netip"
	"os"
	"path/filepath"
	"strings"
)

// ResolvConfFor renders the resolv.conf an alloc of the given project sees.
//
// The search list is what makes a bare service name work: inside project
// "shop", `postgres` resolves through `postgres.shop.kanea`. That is the
// ergonomic half of PRD §7.1.1: a spec can name a peer without spelling out
// the zone, while the name it actually resolves is still fully qualified.
//
// ndots is left at 1 deliberately. Kubernetes ships ndots:5, which sends every
// dotted name through the whole search list before trying it as written; the
// result is four wasted round trips on names like `api.github.com`. With
// ndots:1, a bare `postgres` (no dots) goes through the search list and a
// `web.shop.kanea` (two dots) is tried as-is first, which is the right answer
// for both shapes.
func ResolvConfFor(project, nameserver string) (string, error) {
	host, _, err := net.SplitHostPort(nameserver)
	if err != nil {
		host = nameserver
	}
	if _, err := netip.ParseAddr(host); err != nil {
		return "", fmt.Errorf("network: nameserver %q is not an address: %w", nameserver, err)
	}
	if err := validateLabelValue("project", project); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# generated by kanea; do not edit\n")
	fmt.Fprintf(&b, "nameserver %s\n", host)
	fmt.Fprintf(&b, "search %s.%s %s\n", project, InternalZone, InternalZone)
	// timeout and attempts bound how long a workload waits on a resolver that
	// has gone away: two seconds twice, not the five-second default.
	b.WriteString("options ndots:1 timeout:2 attempts:2\n")
	return b.String(), nil
}

// WriteResolvConf renders a project's resolv.conf into dir and returns its path,
// for the runtime to bind-mount at /etc/resolv.conf.
//
// One file per project rather than one per alloc: the contents depend only on
// the project's search domain, and a shared read-only file is one inode instead
// of one per alloc.
func WriteResolvConf(dir, project, nameserver string) (string, error) {
	body, err := ResolvConfFor(project, nameserver)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return "", fmt.Errorf("resolv.conf dir: %w", err)
	}

	path := filepath.Join(dir, project+".resolv.conf")
	// 0644: the file is bind-mounted into containers that may run as any uid,
	// and it holds no secret; a nameserver address and a search domain.
	if _, err := writeFileIfChangedMode(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// writeFileIfChangedMode swaps a file in atomically, skipping the write when
// the content already matches, and reports whether it wrote. The temp file
// lives in the same directory (rename is only atomic within a filesystem) but
// carries a leading dot and a .tmp suffix so a half-written file is never
// observed under the target name.
func writeFileIfChangedMode(path string, body []byte, mode os.FileMode) (bool, error) {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return false, fmt.Errorf("state dir %s: %w", dir, err)
	}

	// #nosec G304: path comes from configuration, not from a request, and is
	// the same file this function is about to write.
	if current, err := os.ReadFile(path); err == nil && bytes.Equal(current, body) {
		return false, nil
	}

	tmp := filepath.Join(dir, "."+filepath.Base(path)+".tmp")
	if err := os.WriteFile(tmp, body, mode); err != nil {
		return false, fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		if rmErr := os.Remove(tmp); rmErr != nil && !os.IsNotExist(rmErr) {
			return false, fmt.Errorf("install %s: %w (and temp file left behind: %w)", path, err, rmErr)
		}
		return false, fmt.Errorf("install %s: %w", path, err)
	}
	return true, nil
}

// hostResolvConf is where the node's own resolver configuration lives.
const hostResolvConf = "/etc/resolv.conf"

// HostResolvers reads the node's upstream resolvers, for forwarding names
// outside the internal zone.
//
// Any entry pointing at loopback is dropped. On a host running systemd-resolved
// that is 127.0.0.53, which resolves fine *on the host* and is unreachable from
// inside an alloc's namespace: forwarding there would send every external
// lookup into a black hole that only fails after a timeout.
func HostResolvers() ([]string, error) {
	raw, err := os.ReadFile(hostResolvConf)
	if err != nil {
		return nil, fmt.Errorf("network: read %s: %w", hostResolvConf, err)
	}

	var out []string
	var skippedLoopback bool
	for line := range strings.Lines(string(raw)) {
		fields := strings.Fields(line)
		if len(fields) < 2 || fields[0] != "nameserver" {
			continue
		}
		addr, err := netip.ParseAddr(fields[1])
		if err != nil {
			continue
		}
		if addr.IsLoopback() {
			skippedLoopback = true
			continue
		}
		out = append(out, net.JoinHostPort(addr.String(), "53"))
	}

	if len(out) == 0 {
		if skippedLoopback {
			return nil, fmt.Errorf("network: %s lists only loopback resolvers, which allocs cannot "+
				"reach; pass --dns-upstream with a reachable resolver", hostResolvConf)
		}
		return nil, fmt.Errorf("network: %s lists no usable nameserver", hostResolvConf)
	}
	return out, nil
}
