package network

import (
	"fmt"
	"net"
	"net/netip"
	"os"
	"path/filepath"
	"strings"

	"github.com/m18h/kanea/internal/atomicfile"
)

// ResolvConfFor renders the resolv.conf an alloc of the given project sees.
//
// The search list is what makes a bare service name work: inside project
// "shop", `postgres` resolves through `postgres.shop.kanea`. That is the
// ergonomic half of PRD §7.1.1: a spec can name a peer without spelling out
// the zone, while the name it actually resolves is still fully qualified.
//
// ndots is left at 1 deliberately. Kubernetes ships ndots:5, which sends every
// dotted name through the whole search list before trying it as written; the
// result is four wasted round trips on names like `api.github.com`. With
// ndots:1, a bare `postgres` (no dots) goes through the search list and a
// `web.shop.kanea` (two dots) is tried as-is first, which is the right answer
// for both shapes.
func ResolvConfFor(project, nameserver string) (string, error) {
	host, _, err := net.SplitHostPort(nameserver)
	if err != nil {
		host = nameserver
	}
	if _, err := netip.ParseAddr(host); err != nil {
		return "", fmt.Errorf("network: nameserver %q is not an address: %w", nameserver, err)
	}
	if err := validateLabelValue("project", project); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# generated by kanea; do not edit\n")
	fmt.Fprintf(&b, "nameserver %s\n", host)
	fmt.Fprintf(&b, "search %s.%s %s\n", project, InternalZone, InternalZone)
	// timeout and attempts bound how long a workload waits on a resolver that
	// has gone away: two seconds twice, not the five-second default.
	b.WriteString("options ndots:1 timeout:2 attempts:2\n")
	return b.String(), nil
}

// WriteResolvConf renders a project's resolv.conf into dir and returns its path,
// for the runtime to bind-mount at /etc/resolv.conf.
//
// One file per project rather than one per alloc: the contents depend only on
// the project's search domain, and a shared read-only file is one inode instead
// of one per alloc.
func WriteResolvConf(dir, project, nameserver string) (string, error) {
	body, err := ResolvConfFor(project, nameserver)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return "", fmt.Errorf("resolv.conf dir: %w", err)
	}

	path := filepath.Join(dir, project+".resolv.conf")
	// 0644: the file is bind-mounted into containers that may run as any uid,
	// and it holds no secret; a nameserver address and a search domain.
	if _, err := writeFileIfChangedMode(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// writeFileIfChangedMode swaps a file in atomically, skipping the write when
// the content already matches, and reports whether it wrote. The temp file
// lives in the same directory (rename is only atomic within a filesystem) but
// carries a leading dot and a .tmp suffix so a half-written file is never
// observed under the target name.
func writeFileIfChangedMode(path string, body []byte, mode os.FileMode) (bool, error) {
	return atomicfile.WriteIfChanged(path, body, mode)
}

// hostResolvConf is where the node's own resolver configuration lives.
const hostResolvConf = "/etc/resolv.conf"

// HostResolvers reads the node's upstream resolvers, for forwarding names
// outside the internal zone.
//
// Every nameserver is kept, loopback included, and the file's order is the
// host's own preference order. A loopback entry used to be dropped on the
// grounds that an alloc cannot reach it, which named the wrong reader: an
// alloc never receives these addresses. Its /etc/resolv.conf carries the
// internal resolver and nothing else (WriteResolvConf), and the only consumer
// of this list is kanead's own forwarder, which dials from kanead's network
// namespace with a plain net.Dialer - so 127.0.0.53 is exactly as reachable
// here as it is for any other process on the node.
//
// That mattered because systemd-resolved's stub is the *only* nameserver in
// /etc/resolv.conf on a stock Debian or Ubuntu server, so the drop left
// nothing behind and kanead refused to start on the most ordinary DNS setup
// there is. Forwarding to the stub is also the better answer on its merits:
// it is the host's own resolver, so a workload inherits the node's cache,
// its DNSSEC posture and any split-horizon view a link supplies - which is
// what "the host's own resolvers" in upstreamResolvers means.
func HostResolvers() ([]string, error) {
	raw, err := os.ReadFile(hostResolvConf)
	if err != nil {
		return nil, fmt.Errorf("network: read %s: %w", hostResolvConf, err)
	}

	out := parseResolvers(raw)
	if len(out) == 0 {
		return nil, fmt.Errorf("network: %s lists no usable nameserver", hostResolvConf)
	}
	return out, nil
}

// parseResolvers is HostResolvers without the read: the half a test can drive.
// Entries keep the file's order, which is the host's own preference order.
func parseResolvers(raw []byte) []string {
	var out []string
	for line := range strings.Lines(string(raw)) {
		fields := strings.Fields(line)
		if len(fields) < 2 || fields[0] != "nameserver" {
			continue
		}
		addr, err := netip.ParseAddr(fields[1])
		if err != nil {
			continue
		}
		out = append(out, net.JoinHostPort(addr.String(), "53"))
	}
	return out
}
