# Generated by scripts/update-formula.sh — the release workflow rewrites this
# file on every tag. Edit the script, not this file (PRD §5.2.12, v1.60).
#
# Install:
#     brew tap m18h/kanea https://github.com/m18h/kanea
#     brew trust m18h/kanea
#     brew install kanea
class Kanea < Formula
  desc "Container orchestration in one binary"
  homepage "https://github.com/m18h/kanea"
  version "0.16.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.16.0/kanea_0.16.0_darwin_arm64.tar.gz"
      sha256 "e84752039079b1d4249eaa894a4863738a1592e6e76fc5bc4e250922e2bcaa41"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.16.0/kanea_0.16.0_darwin_amd64.tar.gz"
      sha256 "aac8c6e0461b056b86bf0d82bdd60ab77ad5057434c4a6d47200eb953ea700a4"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.16.0/kanea_0.16.0_linux_arm64.tar.gz"
      sha256 "0da0a8b75276c65099e6bbb5de482b302977c9d333dcd721b3519ed9495e2ced"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.16.0/kanea_0.16.0_linux_amd64.tar.gz"
      sha256 "1afa969ffebc21c18bf35eac0a5b9038c5d466537095eb57f3efe0f0fe0b840e"
    end
  end

  def install
    bin.install "kanea"
  end

  def caveats
    <<~EOS
      The platform (kanead, kanea-edge, kanea init) runs on Linux. On macOS
      this is the authoring CLI: kanea plan validates job specs with file and
      line diagnostics before anything touches a node.

      To set up a Linux node: https://github.com/m18h/kanea#install
    EOS
  end

  test do
    assert_match "kanea v#{version}", shell_output("#{bin}/kanea version")

    # A spec that fails validation proves the real parser is in the binary:
    # plan diagnoses before it dials, so no daemon is needed.
    (testpath/"bad.hcl").write <<~HCL
      service "web" {}
    HCL
    output = shell_output("#{bin}/kanea plan #{testpath}/bad.hcl 2>&1", 1)
    assert_match "problem", output
  end
end
