# Generated by scripts/update-formula.sh — the release workflow rewrites this
# file on every tag. Edit the script, not this file (PRD §5.2.12, v1.60).
#
# Install:
#     brew tap m18h/kanea https://github.com/m18h/kanea
#     brew trust m18h/kanea
#     brew install kanea
class Kanea < Formula
  desc "Container orchestration in one binary"
  homepage "https://github.com/m18h/kanea"
  version "0.18.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.18.0/kanea_0.18.0_darwin_arm64.tar.gz"
      sha256 "8680fbb2082b63f0cc0dc1fe559396de81961e9c29badc3df6124221c6c783e8"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.18.0/kanea_0.18.0_darwin_amd64.tar.gz"
      sha256 "72ca2cb5bb3a9ab40b2f19caeb7d4582005d1a7d6cc8b50e0ab7c30f131b420d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.18.0/kanea_0.18.0_linux_arm64.tar.gz"
      sha256 "2bebb983feaad16a1624dbfbf29be6a912195bb7edc4adc0173226d7087e8940"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.18.0/kanea_0.18.0_linux_amd64.tar.gz"
      sha256 "1528ce46a81b5a8dc976bc9e06ea15d7f12e08ce149fcd20baefc1f07eae4a12"
    end
  end

  def install
    bin.install "kanea"
  end

  def caveats
    <<~EOS
      The platform (kanead, kanea-edge, kanea init) runs on Linux. On macOS
      this is the authoring CLI: kanea plan validates job specs with file and
      line diagnostics before anything touches a node.

      To set up a Linux node: https://github.com/m18h/kanea#install
    EOS
  end

  test do
    assert_match "kanea v#{version}", shell_output("#{bin}/kanea version")

    # A spec that fails validation proves the real parser is in the binary:
    # plan diagnoses before it dials, so no daemon is needed.
    (testpath/"bad.hcl").write <<~HCL
      service "web" {}
    HCL
    output = shell_output("#{bin}/kanea plan #{testpath}/bad.hcl 2>&1", 1)
    assert_match "problem", output
  end
end
