# Generated by scripts/update-formula.sh — the release workflow rewrites this
# file on every tag. Edit the script, not this file (PRD §5.2.12, v1.60).
#
# Install:
#     brew tap m18h/kanea https://github.com/m18h/kanea
#     brew trust m18h/kanea
#     brew install kanea
class Kanea < Formula
  desc "Container orchestration in one binary"
  homepage "https://github.com/m18h/kanea"
  version "0.17.1"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.17.1/kanea_0.17.1_darwin_arm64.tar.gz"
      sha256 "2079223c7e168e444c7fecd51896f00f2849b04a3f2e25b2bdd84231ab305bc3"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.17.1/kanea_0.17.1_darwin_amd64.tar.gz"
      sha256 "dc3795af78443ecd805dde4838510d5c6ba538edbe94db9e24c4da1065262bd0"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.17.1/kanea_0.17.1_linux_arm64.tar.gz"
      sha256 "a4fc8c6b7c1e0b310df95a6493104c05c0ea40b303d60dfa8a3ce4c6d1ed8ce0"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.17.1/kanea_0.17.1_linux_amd64.tar.gz"
      sha256 "a77a83b2ba184e9b3e0c95db6516b99b8dabb5c4c5b6672a5e6a5fe84ed243f9"
    end
  end

  def install
    bin.install "kanea"
  end

  def caveats
    <<~EOS
      The platform (kanead, kanea-edge, kanea init) runs on Linux. On macOS
      this is the authoring CLI: kanea plan validates job specs with file and
      line diagnostics before anything touches a node.

      To set up a Linux node: https://github.com/m18h/kanea#install
    EOS
  end

  test do
    assert_match "kanea v#{version}", shell_output("#{bin}/kanea version")

    # A spec that fails validation proves the real parser is in the binary:
    # plan diagnoses before it dials, so no daemon is needed.
    (testpath/"bad.hcl").write <<~HCL
      service "web" {}
    HCL
    output = shell_output("#{bin}/kanea plan #{testpath}/bad.hcl 2>&1", 1)
    assert_match "problem", output
  end
end
