#!/usr/bin/env bash
# Regenerates Formula/kanea.rb — the Homebrew formula (PRD §5.2.12, v1.60).
#
# This script is the formula's ONLY author. The release workflow runs it after
# publishing, with the tag and the release's own checksums.txt, so the version
# and hashes are never typed by hand and the asset names are read out of the
# checksum file rather than composed a fourth time — release.yml, install.sh
# and cmd/kanea/selfupdate.go already share that naming contract, and this
# script is a reader of its output, not another writer.
#
# A release that predates the darwin archives (v0.13.0 and earlier) yields a
# Linux-only formula: the on_macos block appears exactly when its assets do.
#
#     scripts/update-formula.sh v0.13.0 dist/checksums.txt
set -euo pipefail

die() { printf 'update-formula: %s\n' "$*" >&2; exit 1; }

REPO="${KANEA_REPO:-m18h/kanea}"

[ $# -eq 2 ] || die "usage: update-formula.sh <vX.Y.Z> <checksums.txt>"
TAG="$1"
CHECKSUMS="$2"

# The same grammar check kanea upgrade applies before composing a tag into a
# URL: GitHub's no-release redirect ends in a literal "releases", and anything
# that is not a version must not become a plausible-looking asset name.
case "$TAG" in
  v[0-9]*.[0-9]*.[0-9]*) ;;
  *) die "tag ${TAG} does not look like vX.Y.Z" ;;
esac
[ -r "$CHECKSUMS" ] || die "cannot read ${CHECKSUMS}"

VERSION="${TAG#v}"
BASE="https://github.com/${REPO}/releases/download/${TAG}"

# The hash for one archive, by its exact published name; empty when the
# release does not carry that archive.
sha_for() {
  awk -v name="kanea_${VERSION}_$1.tar.gz" '$2 == name { print $1 }' "$CHECKSUMS"
}

LINUX_AMD64="$(sha_for linux_amd64)"
LINUX_ARM64="$(sha_for linux_arm64)"
DARWIN_AMD64="$(sha_for darwin_amd64)"
DARWIN_ARM64="$(sha_for darwin_arm64)"

# Linux archives have shipped since the first release; a checksums file
# without them is the wrong file, not an older release.
[ -n "$LINUX_AMD64" ] && [ -n "$LINUX_ARM64" ] ||
  die "no linux archives in ${CHECKSUMS} for ${TAG}"

# darwin is both architectures or neither — one without the other means the
# release build half-failed, and a formula generated from it would tell every
# Intel Mac the release does not exist.
if { [ -n "$DARWIN_AMD64" ] && [ -z "$DARWIN_ARM64" ]; } ||
   { [ -z "$DARWIN_AMD64" ] && [ -n "$DARWIN_ARM64" ]; }; then
  die "checksums list one darwin architecture but not the other"
fi

OUT="$(cd "$(dirname "$0")/.." && pwd)/Formula/kanea.rb"
mkdir -p "$(dirname "$OUT")"

MACOS_BLOCK=""
if [ -n "$DARWIN_ARM64" ]; then
  MACOS_BLOCK="$(cat <<EOF

  on_macos do
    on_arm do
      url "${BASE}/kanea_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      url "${BASE}/kanea_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"
    end
  end
EOF
)"
fi

cat > "$OUT" <<EOF
# Generated by scripts/update-formula.sh — the release workflow rewrites this
# file on every tag. Edit the script, not this file (PRD §5.2.12, v1.60).
#
# Install:
#     brew tap ${REPO%%/*}/kanea https://github.com/${REPO}
#     brew trust ${REPO%%/*}/kanea
#     brew install kanea
class Kanea < Formula
  desc "Container orchestration in one binary"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end
${MACOS_BLOCK}
  on_linux do
    on_arm do
      url "${BASE}/kanea_${VERSION}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "${BASE}/kanea_${VERSION}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
    end
  end

  def install
    bin.install "kanea"
  end

  def caveats
    <<~EOS
      The platform (kanead, kanea-edge, kanea init) runs on Linux. On macOS
      this is the authoring CLI: kanea plan validates job specs with file and
      line diagnostics before anything touches a node.

      To set up a Linux node: https://github.com/${REPO}#install
    EOS
  end

  test do
    assert_match "kanea v#{version}", shell_output("#{bin}/kanea version")

    # A spec that fails validation proves the real parser is in the binary:
    # plan diagnoses before it dials, so no daemon is needed.
    (testpath/"bad.hcl").write <<~HCL
      service "web" {}
    HCL
    output = shell_output("#{bin}/kanea plan #{testpath}/bad.hcl 2>&1", 1)
    assert_match "problem", output
  end
end
EOF

printf 'wrote %s for %s\n' "$OUT" "$TAG"
